name: django-lab1

services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web-app:
    container_name: web-app
    image: web-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5040:5040"
    command: "python manage.py runserver 0.0.0.0:5040"
    depends_on:
      - db

volumes:
  postgres_data:
