version: "3.9"

name: lab2

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web-app
    container_name: web-app
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db

volumes:
  postgres-data:
